## CCIT4088 Programming for Data Science 2020/2021--- Individual Project
### Name:Chan Chung Yan
### Student ID:20155104

This is project template for the Individual Project. This is a markdown cell. You can try to type the explanation here.

## Data Collection and Cleaning

You should describe the method of Data Collection and Cleaning in this section.

All the cells below are just examples. You can add any number of cells, and explain your approach in any order.

In [23]:
# Collect and extract the data from the relevant website;
import pandas as pd 
from pandas import Series
import numpy as np
d_201612=pd.read_csv('201612_Eng.csv', skiprows=6)
d_201612
d_201712=pd.read_csv('201712_Eng.csv', skiprows=7)
d_201712
d_201812=pd.read_csv('201812_Eng.csv', skiprows=7)
d_201812
d_201912=pd.read_csv('201912_Eng.csv', skiprows=7)
d_201912
d_202012=pd.read_csv('202012_Eng.csv', skiprows=7)
d_201912

,Date,Hour,Central/Western,Eastern,Kwun Tong,Sham Shui Po,Kwai Chung,Tsuen Wan,Tseung Kwan O,Yuen Long,Tuen Mun,Tung Chung,Tai Po,Sha Tin,Tap Mun,Causeway Bay,Central,Mong Kok
0,2019-12-01,01,4,4,4,4,4,4,4,4,4,3,4,3,4,4,4,4
1,NaN,02,4,4,4,4,4,3,4,3,4,3,3,3,4,4,4,4
2,NaN,03,4,4,4,4,4,3,4,3,4,3,3,3,4,4,4,4
3,NaN,04,4,4,4,4,4,3,3,3,3,3,3,3,3,4,4,4
4,NaN,05,4,3,4,4,3,3,3,3,3,3,3,3,3,3,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
770,NaN,21,4,5,5,5,4,4,5,4,4,4,4,4,4,5,5,5
771,NaN,22,5,5,5,5,4,4,5,4,4,4,4,5,5,5,5,5
772,NaN,23,4,5,5,5,4,4,5,4,4,4,4,4,4,5,5,5
773,NaN,24,4,5,5,5,4,4,5,4,4,4,4,4,4,5,5,4
774,NaN,Daily Max,5,5,5,5,4,4,5,4,4,4,4,5,5,5,5,5

In [24]:
# Take a look at the data
print(d_201612.shape)
print(d_201712.shape)
print(d_201812.shape)
print(d_201912.shape)
print(d_202012.shape)
print(type(d_202012))
print(d_202012.dtypes)
print(pd.notnull(d_202012))

(775, 18)
(775, 18)
(775, 18)
(775, 18)
(775, 20)
<class 'pandas.core.frame.DataFrame'>
Date               object
Hour               object
Central/Western    object
Southern           object
Eastern            object
Kwun Tong          object
Sham Shui Po       object
Kwai Chung         object
Tsuen Wan          object
Tseung Kwan O      object
Yuen Long          object
Tuen Mun           object
Tung Chung         object
Tai Po             object
Sha Tin            object
North              object
Tap Mun            object
Causeway Bay       object
Central            object
Mong Kok           object
dtype: object
      Date  Hour  Central/Western  Southern  Eastern  Kwun Tong  Sham Shui Po  \
0     True  True             True      True     True       True          True
1    False  True             True      True     True       True          True
2    False  True             True      True     True       True          True
3    False  True             True      True     True       True          True
4    False  True             True      True     True       True          True
..     ...   ...              ...       ...      ...        ...           ...
770  False  True             True      True     True       True          True
771  False  True             True      True     True       True          True
772  False  True             True      True     True       True          True
773  False  True             True      True     True       True          True
774  False  True             True      True     True       True          True

     Kwai Chung  Tsuen Wan  Tseung Kwan O  Yuen Long  Tuen Mun  Tung Chung  \
0          True       True           True       True      True        True
1          True       True           True       True      True        True
2          True       True           True       True      True        True
3          True       True           True       True      True        True
4          True       True           True       True      True        True
..          ...        ...            ...        ...       ...         ...
770        True       True           True       True      True        True
771        True       True           True       True      True        True
772        True       True           True       True      True        True
773        True       True           True       True      True        True
774        True       True           True       True      True        True

     Tai Po  Sha Tin  North  Tap Mun  Causeway Bay  Central  Mong Kok
0      True     True   True     True          True     True      True
1      True     True   True     True          True     True      True
2      True     True   True     True          True     True      True
3      True     True   True     True          True     True      True
4      True     True   True     True          True     True      True
..      ...      ...    ...      ...           ...      ...       ...
770    True     True   True     True          True     True      True
771    True     True   True     True          True     True      True
772    True     True   True     True          True     True      True
773    True     True   True     True          True     True      True
774    True     True   True     True          True     True      True

[775 rows x 20 columns]

In [25]:
# Replace all the missing value 
# data.fillna('') ... 
d_201612['Date']=d_201612['Date'].fillna(method='ffill')
print(d_201612)
d_201712['Date']=d_201712['Date'].fillna(method='ffill')
print(d_201712)
d_201812['Date']=d_201812['Date'].fillna(method='ffill')
print(d_201812)
d_201912['Date']=d_201912['Date'].fillna(method='ffill')
print(d_201912)
d_202012['Date']=d_202012['Date'].fillna(method='ffill')
print(d_202012)

           Date       Hour Central/Western Eastern Kwun Tong Sham Shui Po  \
0    2016-12-01         01               4       4         4            4
1    2016-12-01         02               4       4         4            4
2    2016-12-01         03               4       4         4            4
3    2016-12-01         04               4       4         4            4
4    2016-12-01         05               4       3         3            4
..          ...        ...             ...     ...       ...          ...
770  2016-12-31         21               5       5         5            5
771  2016-12-31         22               5       5         4            5
772  2016-12-31         23               4       4         4            4
773  2016-12-31         24               4       4         4            4
774  2016-12-31  Daily Max               6       6         6            6

    Kwai Chung Tsuen Wan Tseung Kwan O Yuen Long Tuen Mun Tung Chung Tai Po  \
0            4         4             4         4        5          3      4
1            4         4             4         4        4          3      4
2            4         4             4         4        4          3      4
3            3         3             4         4        4          3      3
4            3         3             3         4        4          3      4
..         ...       ...           ...       ...      ...        ...    ...
770          6         6             5         6        6          5      5
771          5         5             4         6        6          5      5
772          4         5             4         5        5          5      4
773          4         4             4         5        5          4      4
774          7         9             6         8        8          8      7

    Sha Tin Tap Mun Causeway Bay Central Mong Kok
0         4       4            5       4        4
1         4       4            4       4        4
2         4       4            4       4        4
3         3       4            4       3        4
4         3       4            4       3        3
..      ...     ...          ...     ...      ...
770       5       5            5       5        5
771       5       4            5       5        5
772       4       4            5       4        4
773       4       4            4       4        4
774       6       7            6       6        6

[775 rows x 18 columns]
           Date       Hour Central/Western Eastern Kwun Tong Sham Shui Po  \
0    2017-12-01         01               4       4         3            3
1    2017-12-01         02               3       3         3            2
2    2017-12-01         03               3       3         2            2
3    2017-12-01         04               2       2         2            2
4    2017-12-01         05               2       2         2            2
..          ...        ...             ...     ...       ...          ...
770  2017-12-31         21               5       5         5            5
771  2017-12-31         22               5       5         5            5
772  2017-12-31         23               5       5         5            5
773  2017-12-31         24               5       5         5            4
774  2017-12-31  Daily Max               5       5         5            5

    Kwai Chung Tsuen Wan Tseung Kwan O Yuen Long Tuen Mun Tung Chung Tai Po  \
0            3         3             3         2        2          3      3
1            2         2             3         2        2          2      2
2            2         2             2         2        2          2      2
3            2         2             2         2        2          2      2
4            2         2             2         2        2          2      2
..         ...       ...           ...       ...      ...        ...    ...
770          5         5             5         6        7          4      5
771          5         5             5         5        6          4      5
772          5         5             5         5        6          4      5
773          5         5             5         5        5          5      4
774          6         6             5         7        7          7      6

    Sha Tin Tap Mun Causeway Bay Central Mong Kok
0         3       2            4       4        3
1         2       2            3       3        3
2         2       2            2       3        2
3         2       2            2       2        2
4         2       2            2       2        2
..      ...     ...          ...     ...      ...
770       5       5            5       5        5
771       5       5            5       5        5
772       5       5            5       5        5
773       5       5            5       5        5
774       6       6            6       5        5

[775 rows x 18 columns]
           Date       Hour Central/Western Eastern Kwun Tong Sham Shui Po  \
0    2018-12-01         01               5       5         5            5
1    2018-12-01         02               5       5         5            5
2    2018-12-01         03               5       5         5            5
3    2018-12-01         04               5       5         5            5
4    2018-12-01         05               5       5         5            5
..          ...        ...             ...     ...       ...          ...
770  2018-12-31         21               3       3         3            3
771  2018-12-31         22               3       3         3            3
772  2018-12-31         23               3       3         3            2
773  2018-12-31         24               2       3         3            2
774  2018-12-31  Daily Max               3       3         4            3

    Kwai Chung Tsuen Wan Tseung Kwan O Yuen Long Tuen Mun Tung Chung Tai Po  \
0            5         5             5         4        4          4      5
1            5         5             5         4        4          5      5
2            5         5             5         4        5          5      5
3            5         5             5         4        5          5      5
4            5         5             5         4        4          5      5
..         ...       ...           ...       ...      ...        ...    ...
770          3         3             3         3        3          3      3
771          3         3             3         3        3          3      2
772          2         2             3         3        3          3      2
773          2         2             2         2        3          3      2
774          3         3             3         3        3          4      3

    Sha Tin Tap Mun Causeway Bay Central Mong Kok
0         5       5            5       6        5
1         5       5            5       5        5
2         5       5            5       5        5
3         5       5            5       5        5
4         5       5            5       5        5
..      ...     ...          ...     ...      ...
770       3       2            4       4        3
771       2       2            4       3        3
772       2       2            4       3        3
773       2       2            4       3        3
774       3       2            4       5        4

[775 rows x 18 columns]
           Date       Hour Central/Western Eastern Kwun Tong Sham Shui Po  \
0    2019-12-01         01               4       4         4            4
1    2019-12-01         02               4       4         4            4
2    2019-12-01         03               4       4         4            4
3    2019-12-01         04               4       4         4            4
4    2019-12-01         05               4       3         4            4
..          ...        ...             ...     ...       ...          ...
770  2019-12-31         21               4       5         5            5
771  2019-12-31         22               5       5         5            5
772  2019-12-31         23               4       5         5            5
773  2019-12-31         24               4       5         5            5
774  2019-12-31  Daily Max               5       5         5            5

    Kwai Chung Tsuen Wan Tseung Kwan O Yuen Long Tuen Mun Tung Chung Tai Po  \
0            4         4             4         4        4          3      4
1            4         3             4         3        4          3      3
2            4         3             4         3        4          3      3
3            4         3             3         3        3          3      3
4            3         3             3         3        3          3      3
..         ...       ...           ...       ...      ...        ...    ...
770          4         4             5         4        4          4      4
771          4         4             5         4        4          4      4
772          4         4             5         4        4          4      4
773          4         4             5         4        4          4      4
774          4         4             5         4        4          4      4

    Sha Tin Tap Mun Causeway Bay Central Mong Kok
0         3       4            4       4        4
1         3       4            4       4        4
2         3       4            4       4        4
3         3       3            4       4        4
4         3       3            3       4        4
..      ...     ...          ...     ...      ...
770       4       4            5       5        5
771       5       5            5       5        5
772       4       4            5       5        5
773       4       4            5       5        4
774       5       5            5       5        5

[775 rows x 18 columns]
           Date       Hour Central/Western Southern Eastern Kwun Tong  \
0    2020-12-01         01               3        3       3         3
1    2020-12-01         02               3        3       3         3
2    2020-12-01         03               3        3       3         3
3    2020-12-01         04               3        3       3         3
4    2020-12-01         05               3        3       3         3
..          ...        ...             ...      ...     ...       ...
770  2020-12-31         21               4        4       4         4
771  2020-12-31         22               4        4       4         4
772  2020-12-31         23               3        4       3         4
773  2020-12-31         24               3        3       3         4
774  2020-12-31  Daily Max               4        4       4         4

    Sham Shui Po Kwai Chung Tsuen Wan Tseung Kwan O Yuen Long Tuen Mun  \
0              3          3         3             3         3        3
1              3          3         3             3         3        3
2              3          3         3             3         2        3
3              3          3         2             3         2        3
4              3          3         2             2         2        3
..           ...        ...       ...           ...       ...      ...
770            4          4         4             4         4        4
771            4          4         3             3         4        4
772            4          4         3             3         4        4
773            4          3         3             3         3        4
774            4          4         4             4         4        4

    Tung Chung Tai Po Sha Tin North Tap Mun Causeway Bay Central Mong Kok
0            3      3       3     3       3            4       3        3
1            3      3       3     3       3           3*       3        3
2            2      3       3     2       2            3       3        3
3            2      2       3     2       2           3*       3        3
4            2      2       2     2       2            3       3        2
..         ...    ...     ...   ...     ...          ...     ...      ...
770          3      4       4     4       4            4       4        4
771          3      4       4     4       4            4       4        4
772          3      4       4     4       3            4       4        4
773          3      3       4     3       3            4       4        3
774          3      4       4     4       4            5       5        4

[775 rows x 20 columns]

In [26]:
# Function for data cleaning
d_201612=d_201612.replace('Daily Max',np.nan)
d_201612=d_201612.dropna(subset=['Hour'])
d_201712=d_201712.replace('Daily Max',np.nan)
d_201712=d_201712.dropna(subset=['Hour'])
d_201812=d_201812.replace('Daily Max',np.nan)
d_201812=d_201812.dropna(subset=['Hour'])
d_201912=d_201912.replace('Daily Max',np.nan)
d_201912=d_201912.dropna(subset=['Hour'])
d_202012=d_202012.replace('Daily Max',np.nan)
d_202012=d_202012.dropna(subset=['Hour'])
print(d_202012)
def data_cleaning(data):
    data=data.replace('10+','11',regex=True)
    data=data.replace('[*,+]','', regex=True)
    data=data.replace(np.nan, '0', regex=True)
    return data

           Date Hour Central/Western Southern Eastern Kwun Tong Sham Shui Po  \
0    2020-12-01   01               3        3       3         3            3
1    2020-12-01   02               3        3       3         3            3
2    2020-12-01   03               3        3       3         3            3
3    2020-12-01   04               3        3       3         3            3
4    2020-12-01   05               3        3       3         3            3
..          ...  ...             ...      ...     ...       ...          ...
769  2020-12-31   20               4        4       4         4            4
770  2020-12-31   21               4        4       4         4            4
771  2020-12-31   22               4        4       4         4            4
772  2020-12-31   23               3        4       3         4            4
773  2020-12-31   24               3        3       3         4            4

    Kwai Chung Tsuen Wan Tseung Kwan O Yuen Long Tuen Mun Tung Chung Tai Po  \
0            3         3             3         3        3          3      3
1            3         3             3         3        3          3      3
2            3         3             3         2        3          2      3
3            3         2             3         2        3          2      2
4            3         2             2         2        3          2      2
..         ...       ...           ...       ...      ...        ...    ...
769          4         4             4         4        4          3      4
770          4         4             4         4        4          3      4
771          4         3             3         4        4          3      4
772          4         3             3         4        4          3      4
773          3         3             3         3        4          3      3

    Sha Tin North Tap Mun Causeway Bay Central Mong Kok
0         3     3       3            4       3        3
1         3     3       3           3*       3        3
2         3     2       2            3       3        3
3         3     2       2           3*       3        3
4         2     2       2            3       3        2
..      ...   ...     ...          ...     ...      ...
769       4     4       4            5       5        4
770       4     4       4            4       4        4
771       4     4       4            4       4        4
772       4     4       3            4       4        4
773       4     3       3            4       4        3

[744 rows x 20 columns]

In [27]:
# Call the data_cleaning method 
dc_201612= data_cleaning(d_201612)
dc_201712= data_cleaning(d_201712)
dc_201812= data_cleaning(d_201812)
dc_201912= data_cleaning(d_201912)
dc_202012= data_cleaning(d_202012)
dc_202012

,Date,Hour,Central/Western,Southern,Eastern,Kwun Tong,Sham Shui Po,Kwai Chung,Tsuen Wan,Tseung Kwan O,Yuen Long,Tuen Mun,Tung Chung,Tai Po,Sha Tin,North,Tap Mun,Causeway Bay,Central,Mong Kok
0,2020-12-01,01,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,4,3,3
1,2020-12-01,02,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
2,2020-12-01,03,3,3,3,3,3,3,3,3,2,3,2,3,3,2,2,3,3,3
3,2020-12-01,04,3,3,3,3,3,3,2,3,2,3,2,2,3,2,2,3,3,3
4,2020-12-01,05,3,3,3,3,3,3,2,2,2,3,2,2,2,2,2,3,3,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
769,2020-12-31,20,4,4,4,4,4,4,4,4,4,4,3,4,4,4,4,5,5,4
770,2020-12-31,21,4,4,4,4,4,4,4,4,4,4,3,4,4,4,4,4,4,4
771,2020-12-31,22,4,4,4,4,4,4,3,3,4,4,3,4,4,4,4,4,4,4
772,2020-12-31,23,3,4,3,4,4,4,3,3,4,4,3,4,4,4,3,4,4,4
773,2020-12-31,24,3,3,3,4,4,3,3,3,3,4,3,3,4,3,3,4,4,3

## Basic Analysis

#### Q1. Find the daily mean, variance, minimum and maximum AQHI of your home district on your birthday in 2019 (e.g., Kwun Tong,  01 January 2019)

In [28]:
# Codes for answering Q1
dc_201912_by_date=dc_201912.groupby('Date')
print(dc_201912_by_date)
date_2019_1217 =dc_201912_by_date.get_group('2019-12-17')
print(date_2019_1217)
mean_kt_2019_1217= date_2019_1217['Kwun Tong'].astype(float).mean()
print('Mean of AQHI of Kwun Tong on 2019-12-17 :',mean_kt_2019_1217)
v_kt_2019_1217=(date_2019_1217['Kwun Tong'].astype(float)).var()
print('Varience of AQHI of Kwun Tong on 2019-12-17 :',v_kt_2019_1217)
max_kt_2019_1217=max(date_2019_1217['Kwun Tong'].astype(float))
print('Maximum of AQHI of Kwun Tong on 2019-12-17 :',max_kt_2019_1217)
min_kt_2019_1217=min(date_2019_1217['Kwun Tong'].astype(float))
print('Minimum of AQHI of Kwun Tong on 2019-12-17 :',min_kt_2019_1217)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x000001C4B84D0460>
           Date Hour Central/Western Eastern Kwun Tong Sham Shui Po  \
400  2019-12-17   01               3       3         3            3
401  2019-12-17   02               3       3         3            3
402  2019-12-17   03               3       3         3            3
403  2019-12-17   04               3       3         3            3
404  2019-12-17   05               3       3         3            3
405  2019-12-17   06               3       3         3            3
406  2019-12-17   07               3       3         3            3
407  2019-12-17   08               3       3         3            3
408  2019-12-17   09               3       3         3            3
409  2019-12-17   11               3       3         3            3
410  2019-12-17   11               3       3         3            3
411  2019-12-17   12               3       3         3            3
412  2019-12-17   13               3       3         3            3
413  2019-12-17   14               3       3         3            3
414  2019-12-17   15               3       3         3            4
415  2019-12-17   16               3       3         3            4
416  2019-12-17   17               3       3         3            4
417  2019-12-17   18               3       3         3            4
418  2019-12-17   19               3       3         3            4
419  2019-12-17   20               3       3         3            4
420  2019-12-17   21               3       3         3            3
421  2019-12-17   22               3       3         3            3
422  2019-12-17   23               3       3         3            3
423  2019-12-17   24               3       3         3            3

    Kwai Chung Tsuen Wan Tseung Kwan O Yuen Long Tuen Mun Tung Chung Tai Po  \
400          3         3             3         3        3          3      3
401          3         2             3         3        3          3      3
402          3         2             3         3        3          2      3
403          3         2             3         2        3          2      3
404          3         2             3         2        3          2      3
405          3         2             3         2        3          2      3
406          3         2             3         2        3          2      3
407          3         2             3         2        3          2      3
408          3         2             3         3        3          3      3
409          3         3             3         3        3          3      3
410          3         3             3         3        3          3      3
411          3         3             3         3        3          4      3
412          3         4             3         3        4          4      3
413          4         4             3         3        4          5      3
414          4         4             3         4        4          5      4
415          4         5             3         4        4          5      4
416          4         5             3         4        4          5      4
417          4         4             3         5        5          5      4
418          4         4             3         5        5          4      3
419          4         4             3         4        5          4      3
420          3         4             3         4        5          4      3
421          3         3             3         3        4          3      3
422          3         3             3         3        3          3      3
423          3         3             3         3        3          3      2

    Sha Tin Tap Mun Causeway Bay Central Mong Kok
400       3       3            4       4        3
401       3       3            3       4        3
402       3       2            3       3        3
403       3       2            3       4        3
404       3       2            3       4        3
405       3       2            3       3        3
406       3       2            3       3        3
407       3       2            3       3        3
408       3       2            4       4        3
409       3       2            4       4        3
410       3                    4       4        3
411       3                    4       4        4
412       3                    4       4        4
413       3                    4       4        4
414       3                    4       4        4
415       3                    4       4        4
416       3                    4       4        4
417       3                    3       4        4
418       3                    3       4        4
419       3       3            3       4        3
420       3       3            3       3        3
421       3       3            3       3        3
422       3       2            3       3        3
423       3       2            3       3        3
Mean of AQHI of Kwun Tong on 2019-12-17 : 3.0
Varience of AQHI of Kwun Tong on 2019-12-17 : 0.0
Maximum of AQHI of Kwun Tong on 2019-12-17 : 3.0
Minimum of AQHI of Kwun Tong on 2019-12-17 : 3.0

#### Q2. List the day(s) with the worst AQHI of your home district on your birthday month in 2019.

In [23]:
# Codes for answering Q2
max_kt_201912=dc_201912_by_date['Kwun Tong'].max()
max_kt_201912_sort=max_kt_201912.sort_values()
print(max_kt_201912_sort)
print('The worst AQHI of Kwun Tong on December in 2019:')
print (max_kt_201912_sort.tail(1),':',max_kt_201912_sort.max())

Date
2019-12-21    3
2019-12-17    3
2019-12-30    3
2019-12-16    4
2019-12-23    4
2019-12-20    4
2019-12-19    4
2019-12-18    4
2019-12-29    5
2019-12-27    5
2019-12-25    5
2019-12-24    5
2019-12-15    5
2019-12-31    5
2019-12-08    5
2019-12-05    5
2019-12-02    5
2019-12-13    6
2019-12-12    6
2019-12-11    6
2019-12-09    6
2019-12-07    6
2019-12-06    6
2019-12-04    6
2019-12-03    6
2019-12-28    6
2019-12-14    6
2019-12-22    7
2019-12-01    8
2019-12-26    9
Name: Kwun Tong, dtype: object
The worst AQHI of Kwun Tong on December in 2019:
Date
2019-12-26    9
Name: Kwun Tong, dtype: object : 9

## Exploratory analysis

In [24]:
# Your research question / hypothesis
# How would you carry out your research?
# What are your findings?
print('(1)Study the trend of maximum AQHI December from 2016â€“2020 of Kwun Tong')
print('(1a)The maximum AQHI of December from 2016 of Kwun Tong')
dc_201612_by_date= dc_201612.groupby('Date')
max_kt_201612=dc_201612_by_date['Kwun Tong'].max()
max_kt_201612_sort=max_kt_201612.sort_values()
print (max_kt_201612_sort.tail(1),':',max_kt_201612_sort.max(),'\n')

print('(1b)The maximum AQHI of December from 2017 of Kwun Tong')
dc_201712_by_date= dc_201712.groupby('Date')
max_kt_201712=dc_201712_by_date['Kwun Tong'].max()
max_kt_201712_sort=max_kt_201712.sort_values()
print (max_kt_201712_sort.tail(1),':',max_kt_201712_sort.max(),'\n')

print('(1c)The maximum AQHI of December from 2018 of Kwun Tong')
dc_201812_by_date= dc_201812.groupby('Date')
max_kt_201812=dc_201812_by_date['Kwun Tong'].max()
max_kt_201812_sort=max_kt_201812.sort_values()
print (max_kt_201812_sort.tail(1),':',max_kt_201812_sort.max(),'\n')

print('(1d)The maximum AQHI of December from 2019 of Kwun Tong')
dc_201912_by_date= dc_201912.groupby('Date')
max_kt_201912=dc_201912_by_date['Kwun Tong'].max()
max_kt_201912_sort=max_kt_201912.sort_values()
print (max_kt_201912_sort.tail(1),':',max_kt_201912_sort.max(),'\n')

print('(1e)The maximum AQHI of December from 2020 of Kwun Tong')
dc_202012_by_date= dc_202012.groupby('Date')
max_kt_202012=dc_202012_by_date['Kwun Tong'].max()
max_kt_202012_sort=max_kt_202012.sort_values()
print (max_kt_202012_sort.tail(1),':',max_kt_202012_sort.max())

(1)Study the trend of maximum AQHI December from 2016â€“2020 of Kwun Tong
(1a)The maximum AQHI of December from 2016 of Kwun Tong
Date
2016-12-07    7
Name: Kwun Tong, dtype: object : 7

(1b)The maximum AQHI of December from 2017 of Kwun Tong
Date
2017-12-11    9
Name: Kwun Tong, dtype: object : 9

(1c)The maximum AQHI of December from 2018 of Kwun Tong
Date
2018-12-19    6
Name: Kwun Tong, dtype: object : 6

(1d)The maximum AQHI of December from 2019 of Kwun Tong
Date
2019-12-26    9
Name: Kwun Tong, dtype: object : 9

(1e)The maximum AQHI of December from 2020 of Kwun Tong
Date
2020-12-24    7
Name: Kwun Tong, dtype: object : 7

In [32]:
print('(2)Study the seasonal effects on AQHI of Kwun Tong in 2020:')

d_202001=pd.read_csv('202001_Eng.csv', skiprows=7)
d_202002=pd.read_csv('202002_Eng.csv', skiprows=7)
d_202003=pd.read_csv('202003_Eng.csv', skiprows=7)
d_202004=pd.read_csv('202004_Eng.csv', skiprows=7)
d_202005=pd.read_csv('202005_Eng.csv', skiprows=7)
d_202006=pd.read_csv('202006_Eng.csv', skiprows=7)
d_202007=pd.read_csv('202007_Eng.csv', skiprows=7)
d_202008=pd.read_csv('202008_Eng.csv', skiprows=7)
d_202009=pd.read_csv('202009_Eng.csv', skiprows=7)
d_202010=pd.read_csv('202010_Eng.csv', skiprows=7)
d_202011=pd.read_csv('202011_Eng.csv', skiprows=7)
d_202012=pd.read_csv('202012_Eng.csv', skiprows=7)

d_202001['Date']=d_202001['Date'].fillna(method='ffill')
d_202002['Date']=d_202002['Date'].fillna(method='ffill')
d_202003['Date']=d_202003['Date'].fillna(method='ffill')
d_202004['Date']=d_202004['Date'].fillna(method='ffill')
d_202005['Date']=d_202005['Date'].fillna(method='ffill')
d_202006['Date']=d_202006['Date'].fillna(method='ffill')
d_202007['Date']=d_202007['Date'].fillna(method='ffill')
d_202008['Date']=d_202008['Date'].fillna(method='ffill')
d_202009['Date']=d_202009['Date'].fillna(method='ffill')
d_202010['Date']=d_202010['Date'].fillna(method='ffill')
d_202011['Date']=d_202011['Date'].fillna(method='ffill')
d_202012['Date']=d_202012['Date'].fillna(method='ffill')

def data_cleaning(data):
    data=data.replace('10+','11',regex=True)
    data=data.replace('[*,+]','', regex=True)
    data=data.replace(np.nan, '0', regex=True)
    return data

d_202001=d_202001.replace('Daily Max',np.nan)
d_202001=d_202001.dropna(subset=['Hour'])
d_202002=d_202002.replace('Daily Max',np.nan)
d_202002=d_202002.dropna(subset=['Hour'])
d_202003=d_202003.replace('Daily Max',np.nan)
d_202003=d_202003.dropna(subset=['Hour'])
d_202004=d_202004.replace('Daily Max',np.nan)
d_202004=d_202004.dropna(subset=['Hour'])
d_202005=d_202005.replace('Daily Max',np.nan)
d_202005=d_202005.dropna(subset=['Hour'])
d_202006=d_202006.replace('Daily Max',np.nan)
d_202006=d_202006.dropna(subset=['Hour'])
d_202007=d_202007.replace('Daily Max',np.nan)
d_202007=d_202007.dropna(subset=['Hour'])
d_202008=d_202008.replace('Daily Max',np.nan)
d_202008=d_202008.dropna(subset=['Hour'])
d_202009=d_202009.replace('Daily Max',np.nan)
d_202009=d_202009.dropna(subset=['Hour'])
d_202010=d_202010.replace('Daily Max',np.nan)
d_202010=d_202010.dropna(subset=['Hour'])
d_202011=d_202011.replace('Daily Max',np.nan)
d_202011=d_202011.dropna(subset=['Hour'])
d_202012=d_202012.replace('Daily Max',np.nan)
d_202012=d_202012.dropna(subset=['Hour'])

dc_202001= data_cleaning(d_202001)
dc_202002= data_cleaning(d_202002)
dc_202003= data_cleaning(d_202003)
dc_202004= data_cleaning(d_202004)
dc_202005= data_cleaning(d_202005)
dc_202006= data_cleaning(d_202006)
dc_202007= data_cleaning(d_202007)
dc_202008= data_cleaning(d_202008)
dc_202009= data_cleaning(d_202009)
dc_202010= data_cleaning(d_202010)
dc_202011= data_cleaning(d_202011)
dc_202012= data_cleaning(d_202012)

mean_kt_202001= dc_202001['Kwun Tong'].astype(float).mean()
print('(2a(i))The mean on AQHI of Kwun Tong in January 2020:',mean_kt_202001)
dc_202001_by_date=dc_202001.groupby('Date')
max_kt_202001=dc_202001_by_date['Kwun Tong'].max()
p=max_kt_202001.sort_values()
print('(2a(ii))Maximum of AQHI of Kwun Tong in January 2020:')
print(max_kt_202001_sort.tail(1),':',max_kt_202001_sort.max(),'\n')


mean_kt_202002= dc_202002['Kwun Tong'].astype(float).mean()
print('(2b(i))The mean on AQHI of Kwun Tong in February 2020:',mean_kt_202002)
dc_202002_by_date=dc_202002.groupby('Date')
max_kt_202002=dc_202002_by_date['Kwun Tong'].max()
max_kt_202002_sort=max_kt_202002.sort_values()
print('(2b(ii))Maximum of AQHI of Kwun Tong in February 2020 :')
print(max_kt_202002_sort.tail(1),':',max_kt_202002_sort.max(),'\n')

mean_kt_202003= dc_202003['Kwun Tong'].astype(float).mean()
print('(2c(i))The mean on AQHI of Kwun Tong in March 2020:',mean_kt_202003)
dc_202003_by_date=dc_202003.groupby('Date')
max_kt_202003=dc_202003_by_date['Kwun Tong'].max()
max_kt_202003_sort=max_kt_202003.sort_values()
print('(2c(ii))Maximum of AQHI of Kwun Tong in March 2020:')
print(max_kt_202003_sort.tail(1),':',max_kt_202003_sort.max(),'\n')

mean_kt_202004= dc_202004['Kwun Tong'].astype(float).mean()
print('(2d(i))The mean on AQHI of Kwun Tong in April 2020:',mean_kt_202004)
dc_202004_by_date=dc_202004.groupby('Date')
max_kt_202004=dc_202004_by_date['Kwun Tong'].max()
max_kt_202004_sort=max_kt_202004.sort_values()
print('(2d(ii))Maximum of AQHI of Kwun Tong in April 2020:')
print(max_kt_202004_sort.tail(1),':',max_kt_202004_sort.max(),'\n')

mean_kt_202005= dc_202005['Kwun Tong'].astype(float).mean()
print('(2e(i))The mean on AQHI of Kwun Tong in May 2020:',mean_kt_202005)
dc_202005_by_date=dc_202005.groupby('Date')
max_kt_202005=dc_202005_by_date['Kwun Tong'].max()
max_kt_202005_sort=max_kt_202005.sort_values()
print('(2e(ii))Maximum of AQHI of Kwun Tong in May 2020:')
print(max_kt_202005_sort.tail(1),':',max_kt_202005_sort.max(),'\n')

mean_kt_202006= dc_202006['Kwun Tong'].astype(float).mean()
print('(2f(i))The mean on AQHI of Kwun Tong in June 2020:',mean_kt_202006)
dc_202006_by_date=dc_202006.groupby('Date')
max_kt_202006=dc_202006_by_date['Kwun Tong'].max()
max_kt_202006_sort=max_kt_202006.sort_values()
print('(2f(ii))Maximum of AQHI of Kwun Tong in June 2020:')
print(max_kt_202006_sort.tail(1),':',max_kt_202006_sort.max(),'\n')

mean_kt_202007= dc_202007['Kwun Tong'].astype(float).mean()
print('(2g(i))The mean on AQHI of Kwun Tong in July 2020:',mean_kt_202007)
dc_202007_by_date=dc_202007.groupby('Date')
max_kt_202007=dc_202007_by_date['Kwun Tong'].max()
max_kt_202007_sort=max_kt_202007.sort_values()
print('(2g(ii))Maximum of AQHI of Kwun Tong in July 2020:')
print(max_kt_202007_sort.tail(1),':',max_kt_202007_sort.max(),'\n')

mean_kt_202008= dc_202008['Kwun Tong'].astype(float).mean()
print('(2h(i))The mean on AQHI of Kwun Tong in August 2020:',mean_kt_202008)
dc_202008_by_date=dc_202008.groupby('Date')
max_kt_202008=dc_202008_by_date['Kwun Tong'].max()
max_kt_202008_sort=max_kt_202008.sort_values()
print('(2h(ii))Maximum of AQHI of Kwun Tong in August 2020:')
print(max_kt_202008_sort.tail(1),':',max_kt_202008_sort.max(),'\n')

mean_kt_202009= dc_202009['Kwun Tong'].astype(float).mean()
print('(2i(i))The mean on AQHI of Kwun Tong in September 2020:',mean_kt_202009)
dc_202009_by_date=dc_202009.groupby('Date')
max_kt_202009=dc_202009_by_date['Kwun Tong'].max()
max_kt_202009_sort=max_kt_202009.sort_values()
print('(2i(ii))Maximum of AQHI of Kwun Tong in September 2020:')
print(max_kt_202009_sort.tail(1),':',max_kt_202009_sort.max(),'\n')

mean_kt_202010= dc_202010['Kwun Tong'].astype(float).mean()
print('(2j(i))The mean on AQHI of Kwun Tong in October 2020:',mean_kt_202010)
dc_202010_by_date=dc_202010.groupby('Date')
max_kt_202010=dc_202010_by_date['Kwun Tong'].max()
max_kt_202010_sort=max_kt_202010.sort_values()
print('(2j(ii))Maximum of AQHI of Kwun Tong in October 2020:')
print(max_kt_202010_sort.tail(1),':',max_kt_202010_sort.max(),'\n')

mean_kt_202011= dc_202011['Kwun Tong'].astype(float).mean()
print('(2k(i))The mean on AQHI of Kwun Tong in November 2020:',mean_kt_202011)
dc_202011_by_date=dc_202011.groupby('Date')
max_kt_202011=dc_202011_by_date['Kwun Tong'].max()
max_kt_202011_sort=max_kt_202011.sort_values()
print('(2k(ii))Maximum of AQHI of Kwun Tong in November 2020:')
print(max_kt_202011_sort.tail(1),':',max_kt_202011_sort.max(),'\n')

mean_kt_202012= dc_202012['Kwun Tong'].astype(float).mean()
print('(2l(i))The mean on AQHI of Kwun Tong in December 2020:',mean_kt_202012)
dc_202012_by_date=dc_202012.groupby('Date')
max_kt_202012=dc_202012_by_date['Kwun Tong'].max()
max_kt_202012_sort=max_kt_202012.sort_values()
print('(2l(ii))Maximum of AQHI of Kwun Tong in December 2020:')
print(max_kt_202012_sort.tail(1),':',max_kt_202012_sort.max(),'\n')


mean1=pd.Series([mean_kt_202012,mean_kt_202001,mean_kt_202002])
print('(2m(i))Mean of AQHI of Kwun Tong in winter 2020:',mean1.mean(),'\n')
mean2=pd.Series([mean_kt_202003,mean_kt_202004,mean_kt_202005])
print('(2m(ii))Mean of AQHI of Kwun Tong in spring 2020:',mean2.mean(),'\n')
mean3=pd.Series([mean_kt_202006,mean_kt_202007,mean_kt_202008])
print('(2m(iii))Mean of AQHI of Kwun Tong in summer 2020:',mean3.mean(),'\n')
mean4=pd.Series([mean_kt_202009,mean_kt_202010,mean_kt_202011])
print('(2m(iv))Mean of AQHI of Kwun Tong in autumn 2020:',mean4.mean(),'\n')

print('(2n(i))Maximum of AQHI of Kwun Tong in winter 2020:')
max1=pd.Series([max_kt_202012_sort.tail(1),max_kt_202001_sort.tail(1),max_kt_202002_sort.tail(1)])
max1a=max1.astype(str)
print(max1a.max(),'\n')

print('(2n(ii))Maximum of AQHI of Kwun Tong in spring 2020:')
max2=pd.Series([max_kt_202003_sort.tail(1),max_kt_202004_sort.tail(1),max_kt_202005_sort.tail(1)])
max2a=max2.astype(str)
print(max2a.max(),'\n')

print('(2n(iii))Maximum of AQHI of Kwun Tong in summer 2020:')
max3=pd.Series([max_kt_202006_sort.tail(1),max_kt_202007_sort.tail(1),max_kt_202008_sort.tail(1)])
max3a=max3.astype(str)
print(max3a.max(),'\n')

print('(2n(iv))Maximum of AQHI of Kwun Tong in autumn 2020:')
max4=pd.Series([max_kt_202009_sort.tail(1),max_kt_202010_sort.tail(1),max_kt_202011_sort.tail(1)])
max4a=max4.astype(str)
print(max4a.max(),'\n')

(2)Study the seasonal effects on AQHI of Kwun Tong in 2020:
(2a(i))The mean on AQHI of Kwun Tong in January 2020: 3.717741935483871
(2a(ii))Maximum of AQHI of Kwun Tong in January 2020:
Date
2020-01-04    6
Name: Kwun Tong, dtype: object : 6

(2b(i))The mean on AQHI of Kwun Tong in February 2020: 3.3520114942528734
(2b(ii))Maximum of AQHI of Kwun Tong in February 2020 :
Date
2020-02-01    5
Name: Kwun Tong, dtype: object : 5

(2c(i))The mean on AQHI of Kwun Tong in March 2020: 3.5403225806451615
(2c(ii))Maximum of AQHI of Kwun Tong in March 2020:
Date
2020-03-16    6
Name: Kwun Tong, dtype: object : 6

(2d(i))The mean on AQHI of Kwun Tong in April 2020: 3.8375
(2d(ii))Maximum of AQHI of Kwun Tong in April 2020:
Date
2020-04-26    8
Name: Kwun Tong, dtype: object : 8

(2e(i))The mean on AQHI of Kwun Tong in May 2020: 2.911290322580645
(2e(ii))Maximum of AQHI of Kwun Tong in May 2020:
Date
2020-05-11    6
Name: Kwun Tong, dtype: object : 6

(2f(i))The mean on AQHI of Kwun Tong in June 2020: 2.172222222222222
(2f(ii))Maximum of AQHI of Kwun Tong in June 2020:
Date
2020-06-12    4
Name: Kwun Tong, dtype: object : 4

(2g(i))The mean on AQHI of Kwun Tong in July 2020: 2.1908602150537635
(2g(ii))Maximum of AQHI of Kwun Tong in July 2020:
Date
2020-07-25    4
Name: Kwun Tong, dtype: object : 4

(2h(i))The mean on AQHI of Kwun Tong in August 2020: 2.51747311827957
(2h(ii))Maximum of AQHI of Kwun Tong in August 2020:
Date
2020-08-29    7
Name: Kwun Tong, dtype: object : 7

(2i(i))The mean on AQHI of Kwun Tong in September 2020: 3.227777777777778
(2i(ii))Maximum of AQHI of Kwun Tong in September 2020:
Date
2020-09-02    9
Name: Kwun Tong, dtype: object : 9

(2j(i))The mean on AQHI of Kwun Tong in October 2020: 4.235215053763441
(2j(ii))Maximum of AQHI of Kwun Tong in October 2020:
Date
2020-11-24    7
Name: Kwun Tong, dtype: object : 7

(2k(i))The mean on AQHI of Kwun Tong in November 2020: 4.331944444444445
(2k(ii))Maximum of AQHI of Kwun Tong in November 2020:
Date
2020-11-06    9
Name: Kwun Tong, dtype: object : 9

(2l(i))The mean on AQHI of Kwun Tong in December 2020: 3.7876344086021505
(2l(ii))Maximum of AQHI of Kwun Tong in December 2020:
Date
2020-12-24    7
Name: Kwun Tong, dtype: object : 7

(2m(i))Mean of AQHI of Kwun Tong in winter 2020: 3.619129279446298

(2m(ii))Mean of AQHI of Kwun Tong in spring 2020: 3.429704301075269

(2m(iii))Mean of AQHI of Kwun Tong in summer 2020: 2.2935185185185185

(2m(iv))Mean of AQHI of Kwun Tong in autumn 2020: 3.931645758661888

(2n(i))Maximum of AQHI of Kwun Tong in winter 2020:
Date
2020-12-24    7
Name: Kwun Tong, dtype: object

(2n(ii))Maximum of AQHI of Kwun Tong in spring 2020:
Date
2020-05-11    6
Name: Kwun Tong, dtype: object

(2n(iii))Maximum of AQHI of Kwun Tong in summer 2020:
Date
2020-08-29    7
Name: Kwun Tong, dtype: object

(2n(iv))Maximum of AQHI of Kwun Tong in autumn 2020:
Date
2020-11-24    7
Name: Kwun Tong, dtype: object

In [43]:
print('(3)Study the mean on AQHI of Kowloon in November 2020:')
mean_kt_202011= dc_202011['Kwun Tong'].astype(float).mean()
print('(3a)The mean on AQHI of Kwun Tong in November 2020:',mean_kt_202011)
mean_ssp_202011= dc_202011['Sham Shui Po'].astype(float).mean()
print('(3b)The mean on AQHI of Sham Shui Po in November 2020:',mean_ssp_202011)
mean_mk_202011= dc_202011['Mong Kok'].astype(float).mean()
print('(3c)The mean on AQHI of Mong Kok in November 2020:',mean_mk_202011)

(3)Study the mean on AQHI of Kowloon in November 2020:
(3a)The mean on AQHI of Kwun Tong in November 2020: 4.331944444444445
(3b)The mean on AQHI of Sham Shui Po in November 2020: 4.340277777777778
(3c)The mean on AQHI of Mong Kok in November 2020: 4.379166666666666